### ISSUE TITLE
Problems with passwords

### ISSUE THREAD

**Issue by julia-pearson-15** [julia-pearson/wiki_time#1]
I keep getting the 'no method error' for:   

```
'password_digest=' 
```

it says I'm trying to use the method on a hash. Is it being called in my sessions post? bellow:

```
user = User.find_by({name: params[:name]}).try(:authenticate, params[:password])
```

I keep comparing my own code with the 200 cupid but cannot isolate the error. Thank you!

**Comment by annarankin** [comment]
Hey Julia, this was from before, correct?

**Comment by julia-pearson-15** [comment]
correct, thank you!!
