### ISSUE TITLE
can't get javascript working

### ISSUE THREAD

**Issue by julia-pearson-15** [julia-pearson/wiki_time#2]
Hi there. Having a problem linking my Jquery. 
I believe Jquery is linked because when I go into console and try things like:

```
var $navA = $('.nav')[0]
```

It returns the correct answer. (I have three things that come up in an array when I call $('.nav') )
Yet when I try any Jquery method on each variable, I get this error: 

```
Uncaught TypeError: $navA.addClass is not a function
```

Bellow is my full main.js file. All I want is for my navigation bar to bounce when you focus on each tab.

```
var $navBarOne;
var $navBarOne;
var $navBarOne;

var moving = function($element){
  var closure = function(){
    $element.addClass('animated', 'bounce');
  } 
  return closure;
}


$(document).ready(function() {

  $navBarOne = $('.nav')[0];
  $navBarTwo = $('.nav')[1];
  $navBarThree = $('.nav')[2];


  $navBarOne.on('focus', moving($navBarOne));
  $navBarTwo.on('focus', moving($navBarTwo));
  $navBarThree.on('focus', moving($navBarThree));

});
```

**Comment by phlco** [comment]
Careful testing that jQuery is loaded by using the `$`.  Chrome dev tools aliases document.querySelector and document.querySelectorAll as `$` and `$$`  

Instead check for jQuery by using the keyword `jQuery`.

Secondly, when you use bracket notation to access elements jQuery selected you're unwrapping the jQuery object and returning the underlying HTML DOM nodes. 

That means you can't call jQuery methods on them.

```
$('p')[0].css // this throws an error because you're calling `.css` on a DOM node, not the jQuery object.
```

To get an element  by index try https://api.jquery.com/eq/

**Comment by annarankin** [comment]
Hey Julia! I'd throw a debugger inside of your `moving` function and make
sure `$element` is indeed a jQuery object.

**Comment by annarankin** [comment]
Whoops, Phil got here first!
